// Builds a dot-matrix map of Latin America (Mexico → Tierra del Fuego) from Natural Earth data.
import { readFileSync, writeFileSync } from 'node:fs';
import { feature } from 'topojson-client';
import { geoMercator, geoContains } from 'd3-geo';

const topo = JSON.parse(readFileSync(new URL('../node_modules/world-atlas/countries-50m.json', import.meta.url)));
const countries = feature(topo, topo.objects.countries).features;
const land = feature(topo, topo.objects.land);
const usa = countries.find((c) => c.properties.name === 'United States of America');

// Region of interest: everything south of the US border, west of the Atlantic bulge of Brazil.
const W = 560, H = 900, STEP = 9;
const bbox = { type: 'Feature', geometry: { type: 'MultiPoint', coordinates: [[-117.5, 32.8], [-34.5, -56]] } };
const proj = geoMercator().fitSize([W, H], bbox);

const dots = [];
for (let y = STEP / 2; y < H; y += STEP) {
  for (let x = STEP / 2; x < W; x += STEP) {
    const ll = proj.invert([x, y]);
    if (!ll) continue;
    const [lon, lat] = ll;
    if (lon < -118 || lon > -34 || lat > 33 || lat < -56) continue;
    if (!geoContains(land, ll)) continue;
    if (geoContains(usa, ll)) continue;
    if (lat > 22 && lon > -86) continue; // drop Florida / Bahamas north of Cuba
    if (lon < -88 && lat > -3 && lat < 3) continue; // isolated Pacific islands
    if (lon > -62 && lon < -57 && lat < -50.5 && lat > -53) continue; // isolated South Atlantic islands
    dots.push([Math.round(x * 10) / 10, Math.round(y * 10) / 10]);
  }
}
// Trim to the dots' bounding box so the layout can place the silhouette precisely.
const minX = Math.min(...dots.map((d) => d[0])), minY = Math.min(...dots.map((d) => d[1]));
const maxX = Math.max(...dots.map((d) => d[0])), maxY = Math.max(...dots.map((d) => d[1]));
for (const d of dots) { d[0] = Math.round((d[0] - minX) * 10) / 10; d[1] = Math.round((d[1] - minY) * 10) / 10; }
const BW = Math.ceil(maxX - minX), BH = Math.ceil(maxY - minY);
writeFileSync(new URL('../src/latam-dots.js', import.meta.url),
  `// Generated by scripts/build-map.mjs — ${dots.length} dots, ${BW}x${BH}\nwindow.LATAM = { w: ${BW}, h: ${BH}, step: ${STEP}, dots: ${JSON.stringify(dots)} };\n`);
console.log('dots:', dots.length);
